In [8]:
# 일변수 함수의 수치미분 코드 구현
# 입력으로 함수를 받아서 미분을 수행하는 함수를 하나 구현
# 파이썬은 일급함수를 지원
# 함수의 인자로 다른 함수를 받을 수 있음

def numerical_derivative(f, x):
    # f ==> 미분하려는 함수, x ==> 미분값을 알고자하는 입력값
    delta_x = 1e-4
    print(f'delta_x = {delta_x}')
    # 중앙차분을 이용한 미분을 코드로 표현
    result = (f(x + delta_x) - f(x - delta_x)) / (2 * delta_x)
    return result

def my_func(x):
    return x**2

# 함수 f(x) = x**2 의 미분계수 f'(5)를 구하기

result = numerical_derivative(my_func,5)
result


delta_x = 0.0001


9.999999999976694

In [12]:
import numpy as np

def numerical_derivative(f,x):
    # f : 미분하려는 다변수 함수
    # x : 모든 변수를 포함하는 ndarray

    delta_x = 1e-4
    derivative_x = np.zeros_like(x) # shape을 똑같이 0으로 채움

    it = np.nditer(x,flags = ['multi_index'])

    while not it.finished: # iterator가 끝나지 않을 때까지만 반복 , 즉, 끝나면 반복종료
        idx = it.multi_index # 현재의 index를 추출 => tuple 형태로 리턴
        tmp = x[idx] 
        x[idx] = tmp + delta_x
        fx_plus_delta_x = f(x) # f(x + delta_x)

        x[idx] = tmp - delta_x
        fx_minus_delta_x = f(x) # f(x - delta_x)

        derivative_x[idx] = (fx_plus_delta_x - fx_minus_delta_x) / (2 * delta_x)

        x[idx] = tmp

        it.iternext()
    
    return derivative_x
def my_func(x):
    return x**2
# f'(3.0)을 구하기
result = numerical_derivative(my_func,np.array([3.0]))

result

array([6.])

In [14]:
# 2변수 함수를 다시 만들자
def my_func(input_data):
    x = input_data[0]
    y = input_data[1]

    # f(x) = 2x + 3xy + y^3
    return 2*x + 3*x*y + np.power(y,3) # 제곱

result = numerical_derivative(my_func,np.array([1.0,2.0]))
result

array([ 8.        , 15.00000001])

In [17]:
# 4변수 함수에 대해서 수치미분
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# f'(1.0,2.0,3.0,4.0) 의 값은 얼마?
# 차례대로 w에 대한 w값이 1.0일 때 미분값 
# 차례대로 x에 대한 x값이 2.0일 때 미분값 
# 차례대로 y에 대한 y값이 3.0일 때 미분값 
# 차례대로 z에 대한 z값이 4.0일 때 미분값 
def numerical_derivative(f,x):
    # f : 미분하려는 다변수 함수
    # x : 모든 변수를 포함하는 ndarray

    delta_x = 1e-4
    derivative_x = np.zeros_like(x) # shape을 똑같이 0으로 채움

    it = np.nditer(x,flags = ['multi_index']) # 배열 x를 iterator 로 만들어준다.
    # 다중 배열 사용할 때 옵션 multi_index

    while not it.finished: # iterator가 끝나지 않을 때까지만 반복 , 즉, 끝나면 반복종료
        idx = it.multi_index # 현재의 index를 추출 => tuple 형태로 리턴
        tmp = x[idx] 
        x[idx] = tmp + delta_x
        fx_plus_delta_x = f(x) # f(x + delta_x)

        x[idx] = tmp - delta_x
        fx_minus_delta_x = f(x) # f(x - delta_x)

        derivative_x[idx] = (fx_plus_delta_x - fx_minus_delta_x) / (2 * delta_x)

        x[idx] = tmp

        it.iternext()
    
    return derivative_x

def my_func(input_data):
    w = input_data[0]
    x = input_data[1]
    y = input_data[2]
    z = input_data[3]
    return w*x + x*y*z + 3*w + z*y*y

result = numerical_derivative(my_func,np.array([1.0,2.0,3.0,4.0])) # 정수입력하면 값 이상하게 나옴
result



array([ 5., 13., 32., 15.])